In [1]:
import numpy as np
import pandas as pd
import gc

train = pd.read_csv("train_ver2.csv", low_memory=False,skipinitialspace=True,
                   dtype= {  
                               "sexo":str,
                               "ind_nuevo":str,
                               "ult_fec_cli_1t":str,
                               "indext":str
                          }
                    )

train=train.drop(columns='nomprov')
train.isna().sum()

fecha_dato                      0
ncodpers                        0
ind_empleado                27734
pais_residencia             27734
sexo                        27804
age                         27734
fecha_alta                  27734
ind_nuevo                   27734
antiguedad                  27734
indrel                      27734
ult_fec_cli_1t           13622516
indrel_1mes                149781
tiprel_1mes                149781
indresi                     27734
indext                      27734
conyuemp                 13645501
canal_entrada              186126
indfall                     27734
tipodom                     27735
cod_prov                    93591
ind_actividad_cliente       27734
renta                     2794375
segmento                   189368
ind_ahor_fin_ult1               0
ind_aval_fin_ult1               0
ind_cco_fin_ult1                0
ind_cder_fin_ult1               0
ind_cno_fin_ult1                0
ind_ctju_fin_ult1               0
ind_ctma_fin_ult1               0
ind_ctop_fin_ult1               0
ind_ctpp_fin_ult1               0
ind_deco_fin_ult1               0
ind_deme_fin_ult1               0
ind_dela_fin_ult1               0
ind_ecue_fin_ult1               0
ind_fond_fin_ult1               0
ind_hip_fin_ult1                0
ind_plan_fin_ult1               0
ind_pres_fin_ult1               0
ind_reca_fin_ult1               0
ind_tjcr_fin_ult1               0
ind_valo_fin_ult1               0
ind_viv_fin_ult1                0
ind_nomina_ult1             16063
ind_nom_pens_ult1           16063
ind_recibo_ult1                 0
dtype: int64

In [2]:
""" Consistent dtype (int) for outputs train.iloc[:,24:]
    and replace missing values with 0
"""

# {colName: 'ind_nomina_ult1', missing_values: 16063, input_dtype: 'float', desired_dtype: 'int'}
train["ind_nomina_ult1"].fillna(0,inplace=True)
train["ind_nomina_ult1"] = train["ind_nomina_ult1"].astype(int) 

# {colName: 'ind_nom_pens_ult1', missing_values: 16063, input_dtype: 'float', desired_dtype: 'int'}
train["ind_nom_pens_ult1"].fillna(0,inplace=True)
train["ind_nom_pens_ult1"] = train["ind_nom_pens_ult1"].astype(int)

"""Treat conyuemp and ult_fec_cli_1t - High missing values"""
train["conyuemp"].fillna('N',inplace=True)
#train["conyuemp"].unique()

#train["ult_fec_cli_1t"].notna() = '1'
train.loc[train["ult_fec_cli_1t"].notna(), "ult_fec_cli_1t"] = '1'
train["ult_fec_cli_1t"].fillna('0',inplace=True)
train["ult_fec_cli_1t"] = train["ult_fec_cli_1t"].astype(int) 

train.isna().sum()

fecha_dato                     0
ncodpers                       0
ind_empleado               27734
pais_residencia            27734
sexo                       27804
age                        27734
fecha_alta                 27734
ind_nuevo                  27734
antiguedad                 27734
indrel                     27734
ult_fec_cli_1t                 0
indrel_1mes               149781
tiprel_1mes               149781
indresi                    27734
indext                     27734
conyuemp                       0
canal_entrada             186126
indfall                    27734
tipodom                    27735
cod_prov                   93591
ind_actividad_cliente      27734
renta                    2794375
segmento                  189368
ind_ahor_fin_ult1              0
ind_aval_fin_ult1              0
ind_cco_fin_ult1               0
ind_cder_fin_ult1              0
ind_cno_fin_ult1               0
ind_ctju_fin_ult1              0
ind_ctma_fin_ult1              0
ind_ctop_fin_ult1              0
ind_ctpp_fin_ult1              0
ind_deco_fin_ult1              0
ind_deme_fin_ult1              0
ind_dela_fin_ult1              0
ind_ecue_fin_ult1              0
ind_fond_fin_ult1              0
ind_hip_fin_ult1               0
ind_plan_fin_ult1              0
ind_pres_fin_ult1              0
ind_reca_fin_ult1              0
ind_tjcr_fin_ult1              0
ind_valo_fin_ult1              0
ind_viv_fin_ult1               0
ind_nomina_ult1                0
ind_nom_pens_ult1              0
ind_recibo_ult1                0
dtype: int64

In [3]:
train['renta']=np.log10(train['renta'])
train['renta'].interpolate(method='linear',inplace=True)

train.loc[((train['age']>100))]['age']=np.nan
train['age'].interpolate(method='linear',inplace=True)
train.isna().sum()

/home/samarth/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

fecha_dato                    0
ncodpers                      0
ind_empleado              27734
pais_residencia           27734
sexo                      27804
age                           0
fecha_alta                27734
ind_nuevo                 27734
antiguedad                27734
indrel                    27734
ult_fec_cli_1t                0
indrel_1mes              149781
tiprel_1mes              149781
indresi                   27734
indext                    27734
conyuemp                      0
canal_entrada            186126
indfall                   27734
tipodom                   27735
cod_prov                  93591
ind_actividad_cliente     27734
renta                         0
segmento                 189368
ind_ahor_fin_ult1             0
ind_aval_fin_ult1             0
ind_cco_fin_ult1              0
ind_cder_fin_ult1             0
ind_cno_fin_ult1              0
ind_ctju_fin_ult1             0
ind_ctma_fin_ult1             0
ind_ctop_fin_ult1             0
ind_ctpp_fin_ult1             0
ind_deco_fin_ult1             0
ind_deme_fin_ult1             0
ind_dela_fin_ult1             0
ind_ecue_fin_ult1             0
ind_fond_fin_ult1             0
ind_hip_fin_ult1              0
ind_plan_fin_ult1             0
ind_pres_fin_ult1             0
ind_reca_fin_ult1             0
ind_tjcr_fin_ult1             0
ind_valo_fin_ult1             0
ind_viv_fin_ult1              0
ind_nomina_ult1               0
ind_nom_pens_ult1             0
ind_recibo_ult1               0
dtype: int64

In [4]:
train['indrel_1mes']=train['indrel_1mes'].replace('P',5)
train['indrel_1mes']=pd.Series(train['indrel_1mes'].astype(float), dtype="category")
train['indrel_1mes']=train['indrel_1mes'].replace('nan',np.nan)
train['indrel_1mes']=(train.indrel_1mes.cat.codes.replace(-1, np.nan)
                   .interpolate().astype(int).astype('category')
                   .cat.rename_categories(train.indrel_1mes.cat.categories)).astype(int)
train.isna().sum()

fecha_dato                    0
ncodpers                      0
ind_empleado              27734
pais_residencia           27734
sexo                      27804
age                           0
fecha_alta                27734
ind_nuevo                 27734
antiguedad                27734
indrel                    27734
ult_fec_cli_1t                0
indrel_1mes                   0
tiprel_1mes              149781
indresi                   27734
indext                    27734
conyuemp                      0
canal_entrada            186126
indfall                   27734
tipodom                   27735
cod_prov                  93591
ind_actividad_cliente     27734
renta                         0
segmento                 189368
ind_ahor_fin_ult1             0
ind_aval_fin_ult1             0
ind_cco_fin_ult1              0
ind_cder_fin_ult1             0
ind_cno_fin_ult1              0
ind_ctju_fin_ult1             0
ind_ctma_fin_ult1             0
ind_ctop_fin_ult1             0
ind_ctpp_fin_ult1             0
ind_deco_fin_ult1             0
ind_deme_fin_ult1             0
ind_dela_fin_ult1             0
ind_ecue_fin_ult1             0
ind_fond_fin_ult1             0
ind_hip_fin_ult1              0
ind_plan_fin_ult1             0
ind_pres_fin_ult1             0
ind_reca_fin_ult1             0
ind_tjcr_fin_ult1             0
ind_valo_fin_ult1             0
ind_viv_fin_ult1              0
ind_nomina_ult1               0
ind_nom_pens_ult1             0
ind_recibo_ult1               0
dtype: int64

In [5]:
train['tiprel_1mes']=pd.Series(train['tiprel_1mes'].astype(str), dtype="category")
train['tiprel_1mes']=train['tiprel_1mes'].replace('nan',np.nan)
train['tiprel_1mes']=(train.tiprel_1mes.cat.codes.replace(-1, np.nan)
                   .interpolate().astype(int).astype('category')
                   .cat.rename_categories(train.tiprel_1mes.cat.categories))
train.isna().sum()

fecha_dato                    0
ncodpers                      0
ind_empleado              27734
pais_residencia           27734
sexo                      27804
age                           0
fecha_alta                27734
ind_nuevo                 27734
antiguedad                27734
indrel                    27734
ult_fec_cli_1t                0
indrel_1mes                   0
tiprel_1mes                   0
indresi                   27734
indext                    27734
conyuemp                      0
canal_entrada            186126
indfall                   27734
tipodom                   27735
cod_prov                  93591
ind_actividad_cliente     27734
renta                         0
segmento                 189368
ind_ahor_fin_ult1             0
ind_aval_fin_ult1             0
ind_cco_fin_ult1              0
ind_cder_fin_ult1             0
ind_cno_fin_ult1              0
ind_ctju_fin_ult1             0
ind_ctma_fin_ult1             0
ind_ctop_fin_ult1             0
ind_ctpp_fin_ult1             0
ind_deco_fin_ult1             0
ind_deme_fin_ult1             0
ind_dela_fin_ult1             0
ind_ecue_fin_ult1             0
ind_fond_fin_ult1             0
ind_hip_fin_ult1              0
ind_plan_fin_ult1             0
ind_pres_fin_ult1             0
ind_reca_fin_ult1             0
ind_tjcr_fin_ult1             0
ind_valo_fin_ult1             0
ind_viv_fin_ult1              0
ind_nomina_ult1               0
ind_nom_pens_ult1             0
ind_recibo_ult1               0
dtype: int64

In [6]:
train['canal_entrada']=pd.Series(train['canal_entrada'].astype(str), dtype="category")
train['canal_entrada']=train['canal_entrada'].replace('nan',np.nan)
train['canal_entrada']=(train.canal_entrada.cat.codes.replace(-1, np.nan)
                   .interpolate().astype(int).astype('category')
                   .cat.rename_categories(train.canal_entrada.cat.categories))
train.isna().sum()

fecha_dato                    0
ncodpers                      0
ind_empleado              27734
pais_residencia           27734
sexo                      27804
age                           0
fecha_alta                27734
ind_nuevo                 27734
antiguedad                27734
indrel                    27734
ult_fec_cli_1t                0
indrel_1mes                   0
tiprel_1mes                   0
indresi                   27734
indext                    27734
conyuemp                      0
canal_entrada                 0
indfall                   27734
tipodom                   27735
cod_prov                  93591
ind_actividad_cliente     27734
renta                         0
segmento                 189368
ind_ahor_fin_ult1             0
ind_aval_fin_ult1             0
ind_cco_fin_ult1              0
ind_cder_fin_ult1             0
ind_cno_fin_ult1              0
ind_ctju_fin_ult1             0
ind_ctma_fin_ult1             0
ind_ctop_fin_ult1             0
ind_ctpp_fin_ult1             0
ind_deco_fin_ult1             0
ind_deme_fin_ult1             0
ind_dela_fin_ult1             0
ind_ecue_fin_ult1             0
ind_fond_fin_ult1             0
ind_hip_fin_ult1              0
ind_plan_fin_ult1             0
ind_pres_fin_ult1             0
ind_reca_fin_ult1             0
ind_tjcr_fin_ult1             0
ind_valo_fin_ult1             0
ind_viv_fin_ult1              0
ind_nomina_ult1               0
ind_nom_pens_ult1             0
ind_recibo_ult1               0
dtype: int64

In [7]:
train['segmento']=pd.Series(train['segmento'].astype(str), dtype="category")
train['segmento']=train['segmento'].replace('nan',np.nan)
train['segmento']=(train.segmento.cat.codes.replace(-1, np.nan)
                   .interpolate().astype(int).astype('category')
                   .cat.rename_categories(train.segmento.cat.categories))
train.isna().sum()

fecha_dato                   0
ncodpers                     0
ind_empleado             27734
pais_residencia          27734
sexo                     27804
age                          0
fecha_alta               27734
ind_nuevo                27734
antiguedad               27734
indrel                   27734
ult_fec_cli_1t               0
indrel_1mes                  0
tiprel_1mes                  0
indresi                  27734
indext                   27734
conyuemp                     0
canal_entrada                0
indfall                  27734
tipodom                  27735
cod_prov                 93591
ind_actividad_cliente    27734
renta                        0
segmento                     0
ind_ahor_fin_ult1            0
ind_aval_fin_ult1            0
ind_cco_fin_ult1             0
ind_cder_fin_ult1            0
ind_cno_fin_ult1             0
ind_ctju_fin_ult1            0
ind_ctma_fin_ult1            0
ind_ctop_fin_ult1            0
ind_ctpp_fin_ult1            0
ind_deco_fin_ult1            0
ind_deme_fin_ult1            0
ind_dela_fin_ult1            0
ind_ecue_fin_ult1            0
ind_fond_fin_ult1            0
ind_hip_fin_ult1             0
ind_plan_fin_ult1            0
ind_pres_fin_ult1            0
ind_reca_fin_ult1            0
ind_tjcr_fin_ult1            0
ind_valo_fin_ult1            0
ind_viv_fin_ult1             0
ind_nomina_ult1              0
ind_nom_pens_ult1            0
ind_recibo_ult1              0
dtype: int64

In [8]:
train['cod_prov']=pd.Series(train['cod_prov'].astype(str), dtype="category")
train['cod_prov']=train['cod_prov'].replace('nan',np.nan)
train['cod_prov']=(train.cod_prov.cat.codes.replace(-1, np.nan)
                   .interpolate().astype(int).astype('category')
                   .cat.rename_categories(train.cod_prov.cat.categories))
train.isna().sum()

fecha_dato                   0
ncodpers                     0
ind_empleado             27734
pais_residencia          27734
sexo                     27804
age                          0
fecha_alta               27734
ind_nuevo                27734
antiguedad               27734
indrel                   27734
ult_fec_cli_1t               0
indrel_1mes                  0
tiprel_1mes                  0
indresi                  27734
indext                   27734
conyuemp                     0
canal_entrada                0
indfall                  27734
tipodom                  27735
cod_prov                     0
ind_actividad_cliente    27734
renta                        0
segmento                     0
ind_ahor_fin_ult1            0
ind_aval_fin_ult1            0
ind_cco_fin_ult1             0
ind_cder_fin_ult1            0
ind_cno_fin_ult1             0
ind_ctju_fin_ult1            0
ind_ctma_fin_ult1            0
ind_ctop_fin_ult1            0
ind_ctpp_fin_ult1            0
ind_deco_fin_ult1            0
ind_deme_fin_ult1            0
ind_dela_fin_ult1            0
ind_ecue_fin_ult1            0
ind_fond_fin_ult1            0
ind_hip_fin_ult1             0
ind_plan_fin_ult1            0
ind_pres_fin_ult1            0
ind_reca_fin_ult1            0
ind_tjcr_fin_ult1            0
ind_valo_fin_ult1            0
ind_viv_fin_ult1             0
ind_nomina_ult1              0
ind_nom_pens_ult1            0
ind_recibo_ult1              0
dtype: int64

In [9]:
train.iloc[:,:23]=train.iloc[:,:23].apply(lambda x: x.fillna(x.mode()[0]))

In [10]:
test = pd.read_csv("test_ver2.csv",skipinitialspace=True)
"""Treat conyuemp and ult_fec_cli_1t - High missing values"""
test["conyuemp"].fillna('N',inplace=True)
#test["conyuemp"].unique()

#test["ult_fec_cli_1t"].notna() = '1'
test.loc[test["ult_fec_cli_1t"].notna(), "ult_fec_cli_1t"] = '1'
test["ult_fec_cli_1t"].fillna('0',inplace=True)
test["ult_fec_cli_1t"] = test["ult_fec_cli_1t"].astype(int) 

test=test.apply(lambda x: x.fillna(x.mode()[0]))
test=test.drop(columns='nomprov')
test.isna().sum()

/home/samarth/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (15) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

fecha_dato               0
ncodpers                 0
ind_empleado             0
pais_residencia          0
sexo                     0
age                      0
fecha_alta               0
ind_nuevo                0
antiguedad               0
indrel                   0
ult_fec_cli_1t           0
indrel_1mes              0
tiprel_1mes              0
indresi                  0
indext                   0
conyuemp                 0
canal_entrada            0
indfall                  0
tipodom                  0
cod_prov                 0
ind_actividad_cliente    0
renta                    0
segmento                 0
dtype: int64

In [11]:
train.set_index('ncodpers',inplace=True)
test_train_cols= [i for i in train.columns if '_ult1' in i]
test=test.merge(right=train.loc[(train['fecha_dato']=='2016-04-28'),
                        test_train_cols],how='left',left_on='ncodpers', right_index=True)
train.reset_index(inplace=True)
test=test.sort_index(axis=1)
test=test.drop(columns='fecha_dato')
test.set_index('ncodpers',inplace=True,drop=True)
test.columns=[i+'_0' for i in test.columns]
test.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 929615 entries, 15889 to 660248
Data columns (total 45 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age_0                    929615 non-null  int64
 1   antiguedad_0             929615 non-null  int64
 2   canal_entrada_0          929615 non-null  object
 3   cod_prov_0               929615 non-null  float64
 4   conyuemp_0               929615 non-null  object
 5   fecha_alta_0             929615 non-null  object
 6   ind_actividad_cliente_0  929615 non-null  int64
 7   ind_ahor_fin_ult1_0      925252 non-null  float64
 8   ind_aval_fin_ult1_0      925252 non-null  float64
 9   ind_cco_fin_ult1_0       925252 non-null  float64
 10  ind_cder_fin_ult1_0      925252 non-null  float64
 11  ind_cno_fin_ult1_0       925252 non-null  float64
 12  ind_ctju_fin_ult1_0      925252 non-null  float64
 13  ind_ctma_fin_ult1_0      925252 non-null  float64
 14  ind_ctop_fin_ult1_0      925252 non-null  float64
 15  ind_ctpp_fin_ult1_0      925252 non-null  float64
 16  ind_deco_fin_ult1_0      925252 non-null  float64
 17  ind_dela_fin_ult1_0      925252 non-null  float64
 18  ind_deme_fin_ult1_0      925252 non-null  float64
 19  ind_ecue_fin_ult1_0      925252 non-null  float64
 20  ind_empleado_0           929615 non-null  object
 21  ind_fond_fin_ult1_0      925252 non-null  float64
 22  ind_hip_fin_ult1_0       925252 non-null  float64
 23  ind_nom_pens_ult1_0      925252 non-null  float64
 24  ind_nomina_ult1_0        925252 non-null  float64
 25  ind_nuevo_0              929615 non-null  int64
 26  ind_plan_fin_ult1_0      925252 non-null  float64
 27  ind_pres_fin_ult1_0      925252 non-null  float64
 28  ind_reca_fin_ult1_0      925252 non-null  float64
 29  ind_recibo_ult1_0        925252 non-null  float64
 30  ind_tjcr_fin_ult1_0      925252 non-null  float64
 31  ind_valo_fin_ult1_0      925252 non-null  float64
 32  ind_viv_fin_ult1_0       925252 non-null  float64
 33  indext_0                 929615 non-null  object
 34  indfall_0                929615 non-null  object
 35  indrel_0                 929615 non-null  int64
 36  indrel_1mes_0            929615 non-null  float64
 37  indresi_0                929615 non-null  object
 38  pais_residencia_0        929615 non-null  object
 39  renta_0                  929615 non-null  float64
 40  segmento_0               929615 non-null  object
 41  sexo_0                   929615 non-null  object
 42  tipodom_0                929615 non-null  int64
 43  tiprel_1mes_0            929615 non-null  object
 44  ult_fec_cli_1t_0         929615 non-null  int64
dtypes: float64(27), int64(7), object(11)
memory usage: 326.3+ MB

In [12]:
train.set_index('ncodpers',inplace=True)
temp=test.merge(right=train.loc[(train['fecha_dato']=='2016-05-28')],
                how='left',left_index=True, right_index=True).iloc[:,45:]
train.reset_index(inplace=True)
temp=temp.sort_index(axis=1)
temp.columns=[i+'_1' for i in temp.columns]
test=pd.concat([test,temp],axis=1)
test=test.drop(columns='fecha_dato_1')
test.info(verbose=True)
#test.set_index('ncodpers',inplace=True,drop=True)
del temp 
gc.collect()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 929615 entries, 15889 to 660248
Data columns (total 90 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age_0                    929615 non-null  int64
 1   antiguedad_0             929615 non-null  int64
 2   canal_entrada_0          929615 non-null  object
 3   cod_prov_0               929615 non-null  float64
 4   conyuemp_0               929615 non-null  object
 5   fecha_alta_0             929615 non-null  object
 6   ind_actividad_cliente_0  929615 non-null  int64
 7   ind_ahor_fin_ult1_0      925252 non-null  float64
 8   ind_aval_fin_ult1_0      925252 non-null  float64
 9   ind_cco_fin_ult1_0       925252 non-null  float64
 10  ind_cder_fin_ult1_0      925252 non-null  float64
 11  ind_cno_fin_ult1_0       925252 non-null  float64
 12  ind_ctju_fin_ult1_0      925252 non-null  float64
 13  ind_ctma_fin_ult1_0      925252 non-null  float64
 14  ind_ctop_fin_ult1_0      925252 non-null  float64
 15  ind_ctpp_fin_ult1_0      925252 non-null  float64
 16  ind_deco_fin_ult1_0      925252 non-null  float64
 17  ind_dela_fin_ult1_0      925252 non-null  float64
 18  ind_deme_fin_ult1_0      925252 non-null  float64
 19  ind_ecue_fin_ult1_0      925252 non-null  float64
 20  ind_empleado_0           929615 non-null  object
 21  ind_fond_fin_ult1_0      925252 non-null  float64
 22  ind_hip_fin_ult1_0       925252 non-null  float64
 23  ind_nom_pens_ult1_0      925252 non-null  float64
 24  ind_nomina_ult1_0        925252 non-null  float64
 25  ind_nuevo_0              929615 non-null  int64
 26  ind_plan_fin_ult1_0      925252 non-null  float64
 27  ind_pres_fin_ult1_0      925252 non-null  float64
 28  ind_reca_fin_ult1_0      925252 non-null  float64
 29  ind_recibo_ult1_0        925252 non-null  float64
 30  ind_tjcr_fin_ult1_0      925252 non-null  float64
 31  ind_valo_fin_ult1_0      925252 non-null  float64
 32  ind_viv_fin_ult1_0       925252 non-null  float64
 33  indext_0                 929615 non-null  object
 34  indfall_0                929615 non-null  object
 35  indrel_0                 929615 non-null  int64
 36  indrel_1mes_0            929615 non-null  float64
 37  indresi_0                929615 non-null  object
 38  pais_residencia_0        929615 non-null  object
 39  renta_0                  929615 non-null  float64
 40  segmento_0               929615 non-null  object
 41  sexo_0                   929615 non-null  object
 42  tipodom_0                929615 non-null  int64
 43  tiprel_1mes_0            929615 non-null  object
 44  ult_fec_cli_1t_0         929615 non-null  int64
 45  age_1                    929615 non-null  float64
 46  antiguedad_1             929615 non-null  float64
 47  canal_entrada_1          929615 non-null  category
 48  cod_prov_1               929615 non-null  category
 49  conyuemp_1               929615 non-null  object
 50  fecha_alta_1             929615 non-null  object
 51  ind_actividad_cliente_1  929615 non-null  float64
 52  ind_ahor_fin_ult1_1      929615 non-null  int64
 53  ind_aval_fin_ult1_1      929615 non-null  int64
 54  ind_cco_fin_ult1_1       929615 non-null  int64
 55  ind_cder_fin_ult1_1      929615 non-null  int64
 56  ind_cno_fin_ult1_1       929615 non-null  int64
 57  ind_ctju_fin_ult1_1      929615 non-null  int64
 58  ind_ctma_fin_ult1_1      929615 non-null  int64
 59  ind_ctop_fin_ult1_1      929615 non-null  int64
 60  ind_ctpp_fin_ult1_1      929615 non-null  int64
 61  ind_deco_fin_ult1_1      929615 non-null  int64
 62  ind_dela_fin_ult1_1      929615 non-null  int64
 63  ind_deme_fin_ult1_1      929615 non-null  int64
 64  ind_ecue_fin_ult1_1      929615 non-null  int64
 65  ind_empleado_1           929615 non-null  object
 66  ind_fond_fin_ult1_1      929615 non-null  int64
 67  ind_hip_fin_ult1_1       929615 non-null  int64
 68  ind_nom_pens_ult1_1      929615 non-null  int64
 69  ind_nomina_ult1_1        929615 non-null  int64
 70  ind_nuevo_1              929615 non-null  object
 71  ind_plan_fin_ult1_1      929615 non-null  int64
 72  ind_pres_fin_ult1_1      929615 non-null  int64
 73  ind_reca_fin_ult1_1      929615 non-null  int64
 74  ind_recibo_ult1_1        929615 non-null  int64
 75  ind_tjcr_fin_ult1_1      929615 non-null  int64
 76  ind_valo_fin_ult1_1      929615 non-null  int64
 77  ind_viv_fin_ult1_1       929615 non-null  int64
 78  indext_1                 929615 non-null  object
 79  indfall_1                929615 non-null  object
 80  indrel_1                 929615 non-null  float64
 81  indrel_1mes_1            929615 non-null  int64
 82  indresi_1                929615 non-null  object
 83  pais_residencia_1        929615 non-null  object
 84  renta_1                  929615 non-null  float64
 85  segmento_1               929615 non-null  category
 86  sexo_1                   929615 non-null  object
 87  tipodom_1                929615 non-null  float64
 88  tiprel_1mes_1            929615 non-null  category
 89  ult_fec_cli_1t_1         929615 non-null  int64
dtypes: category(4), float64(33), int64(33), object(20)
memory usage: 661.5+ MB

0

In [13]:

test.to_csv('test_final_order2.csv',index=True)
del test
gc.collect()

0

In [14]:
""" Prepare train and test for order n
"""

months = ['2015-01-28', '2015-02-28', '2015-03-28', '2015-04-28', '2015-05-28',
         '2015-06-28', '2015-07-28', '2015-08-28', '2015-09-28', '2015-10-28',
         '2015-11-28', '2015-12-28', '2016-01-28', '2016-02-28', '2016-03-28',
         '2016-04-28', '2016-05-28']

train_X= pd.DataFrame()
train_Y= pd.DataFrame()

order=2

for i in range(len(months)-order+1):
    X=train.loc[train['fecha_dato'].isin(months[i:i+order])]
    X=X.pivot(index='ncodpers', columns='fecha_dato').dropna()
    X.sort_index(axis=1,level=1,inplace=True)
    X.columns = [(col[0]+'_'+str(months[i:i+order].index(col[1]))) 
                 for j,col in enumerate(X.columns.values)]
    X=pd.DataFrame(train['ncodpers'].unique(),columns=['ncodpers']).merge(X,
                        how='left',left_on='ncodpers',right_on='ncodpers').iloc[:,1:]
    Ycols=[k for k in X.columns if 'ult1_'+str(order-1) in k]
    print(months[i:i+order])
    if months[i:i+order][0]!=months[0]:
        train_Y=train_Y.append(X.loc[:,Ycols], ignore_index=True)
        print('Y')
    if months[i:i+order][0]!=months[-order]:
        train_X=train_X.append(X, ignore_index=True)
        print('X')
    Xind=list(X.index)

['2015-01-28', '2015-02-28']
X
['2015-02-28', '2015-03-28']
Y
X
['2015-03-28', '2015-04-28']
Y
X
['2015-04-28', '2015-05-28']
Y
X
['2015-05-28', '2015-06-28']
Y
X
['2015-06-28', '2015-07-28']
Y
X
['2015-07-28', '2015-08-28']
Y
X
['2015-08-28', '2015-09-28']
Y
X
['2015-09-28', '2015-10-28']
Y
X
['2015-10-28', '2015-11-28']
Y
X
['2015-11-28', '2015-12-28']
Y
X
['2015-12-28', '2016-01-28']
Y
X
['2016-01-28', '2016-02-28']
Y
X
['2016-02-28', '2016-03-28']
Y
X
['2016-03-28', '2016-04-28']
Y
X
['2016-04-28', '2016-05-28']
Y

In [15]:
del train
gc.collect()

0

In [16]:
X_complete=train_X.dropna().index
Y_complete=train_Y.dropna().index
Complete=X_complete&Y_complete

In [17]:
train_Y=train_Y.loc[Complete]
train_X=train_X.loc[Complete]

In [18]:
Ynot1 = (train_Y == 0).all(axis=1)
train_Y=train_Y[~Ynot1]
train_X=train_X[~Ynot1]

In [20]:
train_Y.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9662803 entries, 0 to 14340227
Data columns (total 24 columns):
 #   Column               Dtype
---  ------               -----
 0   ind_ahor_fin_ult1_1  float64
 1   ind_aval_fin_ult1_1  float64
 2   ind_cco_fin_ult1_1   float64
 3   ind_cder_fin_ult1_1  float64
 4   ind_cno_fin_ult1_1   float64
 5   ind_ctju_fin_ult1_1  float64
 6   ind_ctma_fin_ult1_1  float64
 7   ind_ctop_fin_ult1_1  float64
 8   ind_ctpp_fin_ult1_1  float64
 9   ind_deco_fin_ult1_1  float64
 10  ind_dela_fin_ult1_1  float64
 11  ind_deme_fin_ult1_1  float64
 12  ind_ecue_fin_ult1_1  float64
 13  ind_fond_fin_ult1_1  float64
 14  ind_hip_fin_ult1_1   float64
 15  ind_nom_pens_ult1_1  float64
 16  ind_nomina_ult1_1    float64
 17  ind_plan_fin_ult1_1  float64
 18  ind_pres_fin_ult1_1  float64
 19  ind_reca_fin_ult1_1  float64
 20  ind_recibo_ult1_1    float64
 21  ind_tjcr_fin_ult1_1  float64
 22  ind_valo_fin_ult1_1  float64
 23  ind_viv_fin_ult1_1   float64
dtypes: float64(24)
memory usage: 1.8 GB

In [21]:
train_X.to_csv('train_X_Final_order2.csv',sep=',',index=False)
train_Y.to_csv('train_Y_Final_order2.csv',sep=',',index=False)
del train_X,train_Y
gc.collect()

0